name: mypy form_teams.py

on:
  push:
    paths:
      - 'form_teams.py'
  pull_request:
    paths:
      - 'form_teams.py'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.x
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Check form_teams.py
        run: mypy form_teams.py --disallow-untyped-defs --disallow-untyped-calls
      - name: Check main
        run: mypy main.py --disallow-untyped-defs --disallow-untyped-calls
      